# Using Matrices To Store Data

- what a matrix is and why matrices are useful.
- How to create matrices using numpy
- Accessing elements of a matrix


Matrix is an ordered set of numbers.
A matrix have to be ordered.

In [1]:
import sympy as sym
import numpy as np
from IPython.display import display, Math

to create a matrix you specify the matrix each row at a time.

In [ ]:
A = [ [1,2],[3,4] ] # the outher brackects define the matrix , the inner brackects define each row
#      1st   2nd
B = np.array(A)
  
display(Math(sym.latex(B)))

display(Math(sym.latex(sym.sympify(B))))

display(Math(sym.latex(sym.Matrix(A)))) #this is another way to create a matrix using sympy 
print(B)
 
type(A) # list
type(B) # numpy.ndarray   

<IPython.core.display.Math object>

<IPython.core.display.Math object>

<IPython.core.display.Math object>

[[1 2]
 [3 4]]


numpy.ndarray

### Creating a Matrix of all Zeroes

In [11]:
np.zeros([3,4]) # 3 rows , 4 columns matrix of all zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
mat = np.zeros([3,4])
mat[0,1] = 5 # access the element at 1st row , 2nd column and set it to 5
display(Math(sym.latex(sym.Matrix(mat))))

<IPython.core.display.Math object>

In [14]:
numrange = range(1,10) # numbers from 1 to 9
mat2 = np.array( [ [i+j*3 for i in numrange[0:3]] for j in range(3) ] )
display(Math(sym.latex(sym.Matrix(mat2))))

<IPython.core.display.Math object>

In [ ]:
numrange = range(0,2) # numbers from 0 to 1
for rowi in numrange:
    for coli in numrange:
        mat[rowi,coli] = (-1)**(rowi+coli)*(rowi+coli)
mat

array([[ 0., -1.,  0.,  0.],
       [-1.,  2., -3.,  4.],
       [ 0.,  0.,  0.,  0.]])

## Matrices Exercise
f(x,y) = (4+x)(2-y)
x,y E {0,1,2}

In [25]:
import sympy as sym
from sympy import Function
import numpy as np
from IPython.display import display, Math
from sympy.abc import x,y

f = Function('f')(x,y)
Fxy = (4+x)*(2-y)
table = np.zeros([3,3])
vals = [0,1,2]
for i in range(3):
    for j in range(3):
        table[i,j] = Fxy.subs({x:vals[i],y:vals[j]})
display(Math(sym.latex(f) + ' = ' + sym.latex(Fxy)))
display(Math(sym.latex(sym.Matrix(table))))

<IPython.core.display.Math object>

<IPython.core.display.Math object>